[tool.poetry]
authors = ["Michael Statt <michael.statt@modelyst.io>", "Kristopher Brown <kris.brown@modelyst.io"]
classifiers = [
  "Environment :: Console",
  "Intended Audience :: Scientists",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
]
description = "DBgen (Database Generator) is an open-source Python library for connecting raw data, scientific theories, and relational databases"
documentation = "https://www.dbgen.modelyst.com"
exclude = ["tests*"]
homepage = "https://www.dbgen.modelyst.com"
include = ["requirements.txt", "LICENSE"]
keywords = ["ETL", "Postgres", "Databases"]
license = "Apache-2.0"
maintainers = ["Michael Statt <michael.statt@modelyst.io>"]
name = "dbgen"
readme = "README.md"
repository = "https://github.com/modelyst/dbgen"
version = "0.4.0"
[tool.poetry.dependencies]
hypothesis = ">=5.23.7"
infinite = ">=0.1"
jinja2 = ">=2.10.0"
networkx = ">=2.4"
pathos = ">=0.2.6"
psycopg2-binary = ">=2.7.4"
sshtunnel = "^0.1.5"
tqdm = ">=4.48.0"
[tool.poetry.dev-dependencies]
hypothesis = ">=5.23.7"
markdown-include = {version = "^0.5.1", extras = ["docs"], optional = true}
mkdocs = {version = "^1.1.2", extras = ["docs"], optional = true}
mkdocs-markdownextradata-plugin = {version = "^0.1.7", extras = ["docs"], optional = true}
mkdocs-material = {version = "^5.5.2", extras = ["docs"], optional = true}
mkdocstrings = {version = "^0.12.2", extras = ["docs"], optional = true}
pdocs = {version = "^1.0.2", extras = ["docs"]}

[tool.poetry.extras]
docs = [
  "markdown",
  "mkdocs",
  "mkdocs",
  "mkdocs",
  "mkdocstrings",
  "pdocs",
]
# [build-system]
# build-backend = "poetry.masonry.api"
# requires = ["poetry>=0.12"]
