name: Feature Request
description: Suggest a feature for DBgen
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Please follow these instructions, fill every question, and do every step. 🙏
  - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I used the GitHub search to find a similar issue and didn't find it.
          required: true
        - label: I searched the DBgen documentation, with the integrated search.
          required: true
        - label: I already read and followed all the tutorial in the docs and didn't find an answer.
          required: true
        - label: I already checked if it is not related to DBgen but to [SQLModel](https://github.com/tiangolo/sqlmodel).
          required: true
  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.

        If I (or someone) can copy it, run it, and see it right away, there's a much higher chance I (or someone) will be able to help you.

      placeholder: |
        from dbgen import Constant, Entity, ETLStep, Model


        class Person(Entity, table=True, all_identifying=True):
            __identifying__ = {"first_name"}
            first_name: str


        def make_model() -> Model:
            model = Model(name="alice_bob_lab")
            with model:
                with ETLStep(name="insert_name"):
                    Person.load(insert=True, first_name=Constant(["Alice"]))

            return model
      render: python
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What is your feature request?

        Write a short description telling me what you are trying to solve and what you are currently doing.
      placeholder: |
        * I would like DBgen to send a slack notification at the end of a run.
    validations:
      required: true
  - type: textarea
    id: wanted-solution
    attributes:
      label: Wanted Solution
      description: |
        Tell me what's the solution you would like.
      placeholder: |
        I would like it to have a `send_slack_notification` configuration that defaults to `False`, and can be set to `True` to send me a slack notification.
    validations:
      required: true
  - type: textarea
    id: wanted-code
    attributes:
      label: Wanted Code
      description: Show me an example of how you would want the code to look like.
      render: python
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        Tell me about alternatives you've considered.
      placeholder: |
        Hire an intern to watch models run and messages me when it finishes
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you on?
      multiple: true
      options:
        - Linux
        - Windows
        - macOS
        - Other
    validations:
      required: true
  - type: textarea
    id: os-details
    attributes:
      label: Operating System Details
      description: You can add more details about your operating system here, in particular if you chose "Other".
  - type: input
    id: dbgen-version
    attributes:
      label: DBgen Version
      description: |
        What DBgen version are you using?

        You can find the DBgen version with:

        ```bash
        dbgen version
        ```
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: |
        What Python version are you using?

        You can find the Python version with:

        ```bash
        python --version
        ```
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any additional context information or screenshots you think are useful.
