name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-root
      - name: Install poetry
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install --force git+https://github.com/python-poetry/poetry-core.git@ad33bc2
          python -m pip install "poetry==1.2.0a2"
      - name: Configure poetry
        run: python -m poetry config virtualenvs.create false
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m poetry install
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.DBGEN_PYPI }}
        run: |
          python -m poetry config pypi-token.pypi $DBGEN_PYPI
          python -m poetry publish --build
